apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: nginx-app-proxy
    # name: nginx-proxy
  name: nginx-default-conf
data:
  default.conf: |-
    error_log /var/log/nginx/error.log;
    server {
      listen      80;
      listen  [::]:80;
      server_name localhost;
      location / {
        root  /usr/share/nginx/html;
        index index.html index.htm;
      }
      error_page  500 502 503 504 /50x.html;
      location = /50x.html {
        root  /usr/share/nginx/html;
      }
      # proxy_set_header  Host  $host;
      proxy_set_header  X-Real-IP  $remote_addr;
      proxy_set_header  X-Forwarded-Host    $host;
      proxy_set_header  X-Forwarded-Server  $host;
      proxy_set_header  X-Forwarded-For  $proxy_add_x_forwarded_for;
      location /test {
        proxy_pass http://192.168.100.166:31222/c0a20060.html;
      }
    }
