apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx-app-proxy
    name: nginx-proxy
  name: nginx-proxy-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-app-proxy
      name: nginx-proxy
  template:
    metadata:
      labels:
        app: nginx-app-proxy
        name: nginx-proxy
    spec:
      containers:
      - name: nginx-proxy
        image: nginx:alpine
        ports:
        - containerPort: 80
          name: nginx-port
          protocol: TCP
        volumeMounts:
        - name: nginx-default-conf-file
          mountPath: /etc/nginx/conf.d/
          readOnly: true
      volumes:
        - name: nginx-default-conf-file
          configMap:
            name: nginx-default-conf
