apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx-app-proxy
    name: nginx-proxy
  name: nginx-proxy-servic
spec:
  selector:
    app: nginx-app-proxy
    name: nginx-proxy
  type: LoadBalancer
  ports:
  - name: nginx-prot
    port: 31333
    protocol: TCP
    targetPort: nginx-port
